version: 2.5.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
assembly_info:
  patch: true
  file: ACT.FFXIVPing\ACT.FFXIVPing*\**\AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    git submodule update --init --recursive
    
    nuget restore ACT.FFXIVPing
build:
  project: ACT.FFXIVPing/ACT.FFXIVPing.sln
  verbosity: minimal
after_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%\ACT.FFXIVPing\ACT.FFXIVPing\bin\%CONFIGURATION%\

    7z a -x!*.pdb %APPVEYOR_BUILD_FOLDER%\ACT.FFXIVPing-%APPVEYOR_BUILD_VERSION%-%CONFIGURATION%.7z .\*

    cp %APPVEYOR_BUILD_FOLDER%\ACT.FFXIVPing\ACT.FFXIVPing\bin\%CONFIGURATION%\ACT.FFXIVPing.dll %APPVEYOR_BUILD_FOLDER%\CafePackage\Plugins\ACT.FFXIVPing

    cd %APPVEYOR_BUILD_FOLDER%\CafePackage

    7z a -tzip -xr!.gitkeep %APPVEYOR_BUILD_FOLDER%\ACT.FFXIVPing-%APPVEYOR_BUILD_VERSION%-%CONFIGURATION%-CAFE.zip .\*
test: off
artifacts:
- path: ACT.FFXIVPing\ACT.FFXIVPing\bin\**\*
  name: Bin
- path: ACT.FFXIVPing*.7z
  name: PKG
- path: ACT.FFXIVPing*.zip
  name: PKG
