//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.FFXIVPing.localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT.FFXIVPing.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 FF14 延迟显示 的本地化字符串。
        /// </summary>
        internal static string actPanelTitle {
            get {
                return ResourceManager.GetString("actPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string buttonCancel {
            get {
                return ResourceManager.GetString("buttonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        internal static string buttonCheckUpdate {
            get {
                return ResourceManager.GetString("buttonCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开下载页面 的本地化字符串。
        /// </summary>
        internal static string buttonDownloadUpdate {
            get {
                return ResourceManager.GetString("buttonDownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改字体 的本地化字符串。
        /// </summary>
        internal static string buttonFont {
            get {
                return ResourceManager.GetString("buttonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除快捷键 的本地化字符串。
        /// </summary>
        internal static string buttonHotkeyNone {
            get {
                return ResourceManager.GetString("buttonHotkeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略错误（插件将无法正常工作） 的本地化字符串。
        /// </summary>
        internal static string buttonIgnore {
            get {
                return ResourceManager.GetString("buttonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 的本地化字符串。
        /// </summary>
        internal static string buttonIgnoreVersion {
            get {
                return ResourceManager.GetString("buttonIgnoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string buttonOk {
            get {
                return ResourceManager.GetString("buttonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置文字 的本地化字符串。
        /// </summary>
        internal static string buttonResetTexts {
            get {
                return ResourceManager.GetString("buttonResetTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置为默认设置 的本地化字符串。
        /// </summary>
        internal static string buttonResetToDefault {
            get {
                return ResourceManager.GetString("buttonResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上一次的设置 的本地化字符串。
        /// </summary>
        internal static string buttonRestoreFromBackup {
            get {
                return ResourceManager.GetString("buttonRestoreFromBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稍后 的本地化字符串。
        /// </summary>
        internal static string buttonUpdateLater {
            get {
                return ResourceManager.GetString("buttonUpdateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string buttonUpdateNow {
            get {
                return ResourceManager.GetString("buttonUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用高级延迟检测 的本地化字符串。
        /// </summary>
        internal static string checkBoxAdvancedPing {
            get {
                return ResourceManager.GetString("checkBoxAdvancedPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悬浮窗自动隐藏 的本地化字符串。
        /// </summary>
        internal static string checkBoxAutoHide {
            get {
                return ResourceManager.GetString("checkBoxAutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动检查更新 的本地化字符串。
        /// </summary>
        internal static string checkBoxCheckUpdate {
            get {
                return ResourceManager.GetString("checkBoxCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标穿透 的本地化字符串。
        /// </summary>
        internal static string checkBoxClickthrough {
            get {
                return ResourceManager.GetString("checkBoxClickthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只提示稳定版更新 的本地化字符串。
        /// </summary>
        internal static string checkBoxNotifyStableOnly {
            get {
                return ResourceManager.GetString("checkBoxNotifyStableOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示悬浮窗 的本地化字符串。
        /// </summary>
        internal static string checkBoxShowOverlay {
            get {
                return ResourceManager.GetString("checkBoxShowOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据... 的本地化字符串。
        /// </summary>
        internal static string defaultOverlayContentNoData {
            get {
                return ResourceManager.GetString("defaultOverlayContentNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ping {ping_ms_na}, 丢包率 {lost}% 的本地化字符串。
        /// </summary>
        internal static string defaultOverlayContentNormal {
            get {
                return ResourceManager.GetString("defaultOverlayContentNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 悬浮窗设置 的本地化字符串。
        /// </summary>
        internal static string groupBoxOverlay {
            get {
                return ResourceManager.GetString("groupBoxOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义文字 的本地化字符串。
        /// </summary>
        internal static string groupBoxTextCustomization {
            get {
                return ResourceManager.GetString("groupBoxTextCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件更新 的本地化字符串。
        /// </summary>
        internal static string groupBoxUpdate {
            get {
                return ResourceManager.GetString("groupBoxUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * 通过启用高级延迟检测，插件将捕获并读取游戏连接的内容，并使用心跳包计算延迟。
        ///
        ///* 这可以得到游戏客户端发送数据包到服务器和接收到响应数据包之间的真实延迟。
        ///
        ///* 但是，由于服务器 Tick Rate 的存在，这个延迟可能会比正常的 Ping 值大得多，并且会有较大的波动。
        ///
        ///* 如果你使用了任何类型的 VPN 软件那么通常你需要启用这个选项。 的本地化字符串。
        /// </summary>
        internal static string labelAdvancedPing {
            get {
                return ResourceManager.GetString("labelAdvancedPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可用变量: {ping} {ping_ms_na} {lost} 的本地化字符串。
        /// </summary>
        internal static string labelAvailableVariables {
            get {
                return ResourceManager.GetString("labelAvailableVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本: 的本地化字符串。
        /// </summary>
        internal static string labelCurrentVersion {
            get {
                return ResourceManager.GetString("labelCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高: 的本地化字符串。
        /// </summary>
        internal static string labelHeight {
            get {
                return ResourceManager.GetString("labelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新稳定版本: 的本地化字符串。
        /// </summary>
        internal static string labelLatestStableVersion {
            get {
                return ResourceManager.GetString("labelLatestStableVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本: 的本地化字符串。
        /// </summary>
        internal static string labelLatestVersion {
            get {
                return ResourceManager.GetString("labelLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言: 的本地化字符串。
        /// </summary>
        internal static string labelMainLanguage {
            get {
                return ResourceManager.GetString("labelMainLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *需要重启ACT。 的本地化字符串。
        /// </summary>
        internal static string labelNeedToRestart {
            get {
                return ResourceManager.GetString("labelNeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不透明度: 的本地化字符串。
        /// </summary>
        internal static string labelOpacity {
            get {
                return ResourceManager.GetString("labelOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据时文字: 的本地化字符串。
        /// </summary>
        internal static string labelOverlayContentNoData {
            get {
                return ResourceManager.GetString("labelOverlayContentNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常状态下文字: 的本地化字符串。
        /// </summary>
        internal static string labelOverlayContentNormal {
            get {
                return ResourceManager.GetString("labelOverlayContentNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        internal static string labelPosition {
            get {
                return ResourceManager.GetString("labelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新间隔 (秒): 的本地化字符串。
        /// </summary>
        internal static string labelRefreshInterval {
            get {
                return ResourceManager.GetString("labelRefreshInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷键: 的本地化字符串。
        /// </summary>
        internal static string labelShortcutHide {
            get {
                return ResourceManager.GetString("labelShortcutHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸 的本地化字符串。
        /// </summary>
        internal static string labelSize {
            get {
                return ResourceManager.GetString("labelSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽: 的本地化字符串。
        /// </summary>
        internal static string labelWidth {
            get {
                return ResourceManager.GetString("labelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版！ 的本地化字符串。
        /// </summary>
        internal static string messageLatest {
            get {
                return ResourceManager.GetString("messageLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的抢鲜版: {0}。 的本地化字符串。
        /// </summary>
        internal static string messageNewPrerelease {
            get {
                return ResourceManager.GetString("messageNewPrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新的稳定版: {0}。 的本地化字符串。
        /// </summary>
        internal static string messageNewStable {
            get {
                return ResourceManager.GetString("messageNewStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待按键... 的本地化字符串。
        /// </summary>
        internal static string messageWaitKey {
            get {
                return ResourceManager.GetString("messageWaitKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法加载当前的设置文件！ 的本地化字符串。
        /// </summary>
        internal static string settingsError {
            get {
                return ResourceManager.GetString("settingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一次的设置文件备份也无法加载！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorBackup {
            get {
                return ResourceManager.GetString("settingsErrorBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以：
        ///1. 重置为默认设置，注意这将导致当前设置丢失！
        ///2. 直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorHintNoBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintNoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你可以：
        ///1.从上一次的设置备份中恢复，注意这将导致当前设置丢失！
        ///2.重置为默认设置，这也将导致当前设置丢失！
        ///3.直接忽略设置文件的错误并继续，这将不会更改任何现有设置，因此你可以手动检查你的设置文件并尝试恢复，但是本插件将无法正常工作！ 的本地化字符串。
        /// </summary>
        internal static string settingsErrorHintWithBackup {
            get {
                return ResourceManager.GetString("settingsErrorHintWithBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        internal static string tabPageAdvanced {
            get {
                return ResourceManager.GetString("tabPageAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规设置 的本地化字符串。
        /// </summary>
        internal static string tabPageGeneralSettings {
            get {
                return ResourceManager.GetString("tabPageGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件日志 的本地化字符串。
        /// </summary>
        internal static string tabPageLog {
            get {
                return ResourceManager.GetString("tabPageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查中... 的本地化字符串。
        /// </summary>
        internal static string updateChecking {
            get {
                return ResourceManager.GetString("updateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string versionUnknown {
            get {
                return ResourceManager.GetString("versionUnknown", resourceCulture);
            }
        }
    }
}
